<?php
define('INSTALL_LOCK', __DIR__ . '/uploads/.installed');

// Already installed?
if (file_exists(INSTALL_LOCK) && !isset($_GET['force'])) {
    die('<div style="font-family:sans-serif;max-width:500px;margin:60px auto;text-align:center;">
        <h2>✅ Already Installed</h2>
        <p>LeadPro LMS is already installed. <a href="login.php">Go to Login</a></p>
        <p style="color:#999;font-size:.85rem;">To re-run installer, add <code>?force=1</code> to the URL.</p>
    </div>');
}

$step    = (int)($_POST['step'] ?? $_GET['step'] ?? 1);
$errors  = [];
$success = false;

// ── STEP 2: Process form & install ───────────────────────────
if ($_SERVER['REQUEST_METHOD'] === 'POST' && $step === 2) {
    $dbHost  = trim($_POST['db_host']  ?? 'localhost');
    $dbPort  = (int)($_POST['db_port'] ?? 3306);
    $dbUser  = trim($_POST['db_user']  ?? '');
    $dbPass  = $_POST['db_pass'] ?? '';
    $dbName  = trim($_POST['db_name']  ?? 'lms_db');
    $appUrl  = rtrim(trim($_POST['app_url'] ?? ''), '/');
    $adminName  = trim($_POST['admin_name']  ?? '');
    $adminEmail = trim($_POST['admin_email'] ?? '');
    $adminPass  = $_POST['admin_pass'] ?? '';
    $companyName= trim($_POST['company_name'] ?? 'My Company');

    if (!$dbUser)         $errors[] = 'Database username is required.';
    if (!$dbName)         $errors[] = 'Database name is required.';
    if (!$adminName)      $errors[] = 'Admin name is required.';
    if (!filter_var($adminEmail, FILTER_VALIDATE_EMAIL)) $errors[] = 'Valid admin email is required.';
    if (strlen($adminPass) < 6) $errors[] = 'Admin password must be at least 6 characters.';

    if (!$errors) {
        try {
            // Test connection
            $dsn = "mysql:host=$dbHost;port=$dbPort;charset=utf8mb4";
            $pdo = new PDO($dsn, $dbUser, $dbPass, [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);

            // Create database if not exists
            $pdo->exec("CREATE DATABASE IF NOT EXISTS `$dbName` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
            $pdo->exec("USE `$dbName`");

            // Run schema
            $sql = file_get_contents(__DIR__ . '/database/schema.sql');

            // Split & remove USE/CREATE DATABASE lines (already done)
            $sql = preg_replace('/^(CREATE DATABASE|USE\s)/im', '-- $0', $sql);
            $statements = array_filter(
                array_map('trim', explode(';', $sql)),
                fn($s) => strlen($s) > 5
            );
            foreach ($statements as $stmt) {
                if (str_starts_with(ltrim($stmt), '--')) continue;
                try { $pdo->exec($stmt . ';'); } catch (PDOException $e) {
                    // Ignore duplicate errors on re-install
                    if ($e->getCode() != '42S01' && $e->getCode() != '23000') throw $e;
                }
            }

            // Update admin user
            $hash = password_hash($adminPass, PASSWORD_BCRYPT, ['cost' => 12]);
            $pdo->prepare("UPDATE users SET name=?,email=?,password=? WHERE role='admin' LIMIT 1")
                ->execute([$adminName, $adminEmail, $hash]);

            // Update company setting
            $pdo->prepare("INSERT INTO settings (setting_key,setting_val) VALUES ('company_name',?) ON DUPLICATE KEY UPDATE setting_val=?")
                ->execute([$companyName, $companyName]);
            $pdo->prepare("INSERT INTO settings (setting_key,setting_val) VALUES ('company_email',?) ON DUPLICATE KEY UPDATE setting_val=?")
                ->execute([$adminEmail, $adminEmail]);

            // Write config
            $configContent = "<?php
// ============================================================
// config.php — Auto-generated by installer
// ============================================================

define('DB_HOST',     '$dbHost');
define('DB_USER',     '$dbUser');
define('DB_PASS',     '$dbPass');
define('DB_NAME',     '$dbName');
define('DB_PORT',     $dbPort);
define('DB_CHARSET',  'utf8mb4');

define('APP_NAME',    'LeadPro LMS');
define('APP_URL',     '$appUrl');
define('APP_VERSION', '1.0.0');

define('UPLOAD_PATH', __DIR__ . '/../uploads/');
define('UPLOAD_URL',  APP_URL . '/uploads/');

define('SESSION_LIFETIME', 3600);

date_default_timezone_set('Asia/Kolkata');

error_reporting(0);
ini_set('display_errors', 0);
";
            file_put_contents(__DIR__ . '/includes/config.php', $configContent);

            // Create lock file
            @mkdir(__DIR__ . '/uploads', 0755, true);
            file_put_contents(INSTALL_LOCK, date('Y-m-d H:i:s'));

            $success = true;
        } catch (PDOException $e) {
            $errors[] = 'Database error: ' . $e->getMessage();
        } catch (Exception $e) {
            $errors[] = 'Installation error: ' . $e->getMessage();
        }
    }
}

// ── Auto-detect app URL ────────────────────────────────────
$protocol  = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https' : 'http';
$host      = $_SERVER['HTTP_HOST'] ?? 'localhost';
$path      = dirname($_SERVER['SCRIPT_NAME'] ?? '/');
$detectedUrl = $protocol . '://' . $host . ($path === '/' ? '' : $path);
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Install LeadPro LMS</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;600;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
<style>
  body { font-family:'Plus Jakarta Sans',sans-serif; background:#f1f5f9; }
  .install-card { max-width:640px; margin:2rem auto; }
  .install-header { background:linear-gradient(135deg,#0f172a,#1e3a5f); color:#fff;
                    border-radius:12px 12px 0 0; padding:2rem; text-align:center; }
  .install-header .icon { width:60px;height:60px;background:#2563eb;border-radius:16px;
                          display:inline-flex;align-items:center;justify-content:center;
                          font-size:1.8rem;margin-bottom:1rem; }
  .card { border-radius:0 0 12px 12px; }
  .steps { display:flex; gap:0; margin-bottom:2rem; }
  .step-item { flex:1; padding:.5rem; text-align:center; font-size:.78rem; font-weight:600;
               border-bottom:3px solid #e2e8f0; color:#94a3b8; }
  .step-item.active { border-color:#2563eb; color:#2563eb; }
  .step-item.done   { border-color:#10b981; color:#10b981; }
  .req-ok   { color:#10b981; }
  .req-warn { color:#f59e0b; }
  .req-fail { color:#ef4444; }
</style>
</head>
<body>
<div class="install-card">
  <div class="install-header">
    <div class="icon"><i class="bi bi-bullseye"></i></div>
    <h1 style="font-size:1.6rem;font-weight:700;margin:0;">LeadPro LMS Installer</h1>
    <p style="opacity:.7;margin:.5rem 0 0;font-size:.9rem;">Version 1.0.0</p>
  </div>

  <div class="card shadow-sm border-0">
    <div class="card-body p-4">

      <?php if ($success): ?>
      <!-- ── SUCCESS ── -->
      <div class="text-center py-3">
        <div style="width:70px;height:70px;background:#d1fae5;border-radius:50%;
                    display:inline-flex;align-items:center;justify-content:center;
                    font-size:2rem;color:#10b981;margin-bottom:1.5rem;">
          <i class="bi bi-check-lg"></i>
        </div>
        <h3 class="fw-700 mb-2">Installation Complete!</h3>
        <p class="text-muted mb-4">
          LeadPro LMS has been installed successfully.<br>
          You can now log in with your admin credentials.
        </p>
        <div class="alert alert-warning py-2 small text-start">
          <i class="bi bi-shield-exclamation me-2"></i>
          <strong>Security:</strong> Please delete <code>install.php</code> from your server immediately!
        </div>
        <a href="login.php" class="btn btn-primary btn-lg px-5 mt-2">
          <i class="bi bi-box-arrow-in-right me-2"></i>Go to Login
        </a>
      </div>

      <?php else: ?>
      <!-- ── STEPS ── -->
      <div class="steps">
        <div class="step-item <?= $step==1?'active':'done' ?>">1. Requirements</div>
        <div class="step-item <?= $step==2?'active':'' ?>">2. Configuration</div>
        <div class="step-item">3. Complete</div>
      </div>

      <?php if ($step === 1): ?>
      <!-- Requirements Check -->
      <?php
        $checks = [
          'PHP >= 8.0' => version_compare(PHP_VERSION, '8.0', '>='),
          'PDO Extension'   => extension_loaded('pdo'),
          'PDO MySQL'       => extension_loaded('pdo_mysql'),
          'cURL Extension'  => extension_loaded('curl'),
          'uploads/ writable' => is_writable(__DIR__ . '/uploads') || @mkdir(__DIR__ . '/uploads', 0755, true),
          'includes/ writable'=> is_writable(__DIR__ . '/includes'),
          'database/schema.sql exists' => file_exists(__DIR__ . '/database/schema.sql'),
        ];
        $allPass = !in_array(false, $checks);
      ?>
      <h5 class="fw-700 mb-3">System Requirements</h5>
      <table class="table table-sm mb-4">
        <tbody>
          <?php foreach ($checks as $label => $pass): ?>
          <tr>
            <td><?= $label ?></td>
            <td class="<?= $pass ? 'req-ok' : 'req-fail' ?>">
              <i class="bi bi-<?= $pass ? 'check-circle-fill' : 'x-circle-fill' ?>"></i>
              <?= $pass ? 'OK' : 'FAIL' ?>
            </td>
          </tr>
          <?php endforeach; ?>
        </tbody>
      </table>
      <div class="text-end">
        <a href="?step=2" class="btn btn-primary <?= $allPass?'':'disabled' ?>">
          Continue <i class="bi bi-arrow-right ms-1"></i>
        </a>
        <?php if (!$allPass): ?>
        <div class="text-danger small mt-2">Please fix the requirements above before continuing.</div>
        <?php endif; ?>
      </div>

      <?php elseif ($step === 2): ?>
      <!-- Configuration Form -->
      <?php foreach ($errors as $err): ?>
      <div class="alert alert-danger py-2 small"><i class="bi bi-exclamation-triangle me-2"></i><?= htmlspecialchars($err) ?></div>
      <?php endforeach; ?>

      <form method="POST">
        <input type="hidden" name="step" value="2">
        <h6 class="fw-700 border-bottom pb-2 mb-3">Database Configuration</h6>
        <div class="row g-3 mb-4">
          <div class="col-md-6">
            <label class="form-label small fw-600">DB Host</label>
            <input type="text" name="db_host" class="form-control form-control-sm"
                   value="<?= htmlspecialchars($_POST['db_host'] ?? 'localhost') ?>" required>
          </div>
          <div class="col-md-2">
            <label class="form-label small fw-600">Port</label>
            <input type="number" name="db_port" class="form-control form-control-sm"
                   value="<?= htmlspecialchars($_POST['db_port'] ?? '3306') ?>">
          </div>
          <div class="col-md-4">
            <label class="form-label small fw-600">Database Name</label>
            <input type="text" name="db_name" class="form-control form-control-sm"
                   value="<?= htmlspecialchars($_POST['db_name'] ?? 'lms_db') ?>" required>
          </div>
          <div class="col-md-6">
            <label class="form-label small fw-600">DB Username</label>
            <input type="text" name="db_user" class="form-control form-control-sm"
                   value="<?= htmlspecialchars($_POST['db_user'] ?? 'root') ?>" required>
          </div>
          <div class="col-md-6">
            <label class="form-label small fw-600">DB Password</label>
            <input type="password" name="db_pass" class="form-control form-control-sm"
                   placeholder="Leave blank if none">
          </div>
        </div>

        <h6 class="fw-700 border-bottom pb-2 mb-3">Application URL</h6>
        <div class="mb-4">
          <label class="form-label small fw-600">App Base URL <span class="text-muted">(no trailing slash)</span></label>
          <input type="url" name="app_url" class="form-control form-control-sm"
                 value="<?= htmlspecialchars($_POST['app_url'] ?? $detectedUrl) ?>" required>
          <div class="form-text">Example: <code>http://localhost/lms</code> or <code>https://yourdomain.com/lms</code></div>
        </div>

        <h6 class="fw-700 border-bottom pb-2 mb-3">Admin Account</h6>
        <div class="row g-3 mb-4">
          <div class="col-md-6">
            <label class="form-label small fw-600">Admin Name</label>
            <input type="text" name="admin_name" class="form-control form-control-sm"
                   value="<?= htmlspecialchars($_POST['admin_name'] ?? 'Super Admin') ?>" required>
          </div>
          <div class="col-md-6">
            <label class="form-label small fw-600">Admin Email</label>
            <input type="email" name="admin_email" class="form-control form-control-sm"
                   value="<?= htmlspecialchars($_POST['admin_email'] ?? '') ?>" required>
          </div>
          <div class="col-md-6">
            <label class="form-label small fw-600">Admin Password</label>
            <input type="password" name="admin_pass" class="form-control form-control-sm"
                   placeholder="Min 6 characters" required>
          </div>
          <div class="col-md-6">
            <label class="form-label small fw-600">Company Name</label>
            <input type="text" name="company_name" class="form-control form-control-sm"
                   value="<?= htmlspecialchars($_POST['company_name'] ?? '') ?>">
          </div>
        </div>

        <div class="d-flex justify-content-between">
          <a href="?step=1" class="btn btn-outline-secondary btn-sm">
            <i class="bi bi-arrow-left me-1"></i>Back
          </a>
          <button type="submit" class="btn btn-primary px-4">
            <i class="bi bi-lightning-fill me-2"></i>Install Now
          </button>
        </div>
      </form>
      <?php endif; ?>
      <?php endif; ?>

    </div>
  </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>
